### ISSUE TITLE
The latest version 1.15.9 causes issue on the Menu component

### ISSUE THREAD

**Issue by Jackson-he** [uiw-react/uiw#63]
![picture](https://user-images.githubusercontent.com/26061572/44827172-91487a80-ac44-11e8-8ba7-99f813ca620b.png)

As you can see from the picture up here, the sidebar can not be folded up as usual.

**Comment by jaywcjlove** [comment]
@Jackson-he let me check

**Comment by jaywcjlove** [comment]
@Jackson-he Attribute value changes

![image](https://user-images.githubusercontent.com/1680273/44828841-4468a200-ac4c-11e8-9e55-29794d6b4b37.png)

```diff
<Menu
-  mode={collapsed ? 'inline' : 'vertical' }
+  mode={collapsed ? 'vertical' : 'inline'}
  inlineCollapsed={collapsed}
  theme="dark"
  defaultActive={defaultActive}
  defaultOpened={defaultOpened}
  onClose={this.onClose.bind(this)}
  onSelect={this.onSelect.bind(this)}
  style={{ width }}
>
  ....
</Menu>
```

**Comment by Jackson-he** [comment]
Thanks, problem solved!
